# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/user/Desktop/project/BARN_AI_FPGA_PL/BARN_AI/BARN AI.srcs/sources_1/bd/image_block/ip/image_block_processing_system7_0_0/image_block_processing_system7_0_0.xci
# IP: The module: 'image_block_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Desktop/project/BARN_AI_FPGA_PL/BARN_AI/BARN AI.gen/sources_1/bd/image_block/ip/image_block_processing_system7_0_0/image_block_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_block_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/user/Desktop/project/BARN_AI_FPGA_PL/BARN_AI/BARN AI.srcs/sources_1/bd/image_block/ip/image_block_processing_system7_0_0/image_block_processing_system7_0_0.xci
# IP: The module: 'image_block_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Desktop/project/BARN_AI_FPGA_PL/BARN_AI/BARN AI.gen/sources_1/bd/image_block/ip/image_block_processing_system7_0_0/image_block_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_block_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
