# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/user/Desktop/project/FPGA/BARN AI/BARN AI.srcs/sources_1/bd/image_block/ip/image_block_rst_ps7_0_100M_0/image_block_rst_ps7_0_100M_0.xci
# IP: The module: 'image_block_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Desktop/project/FPGA/BARN AI/BARN AI.gen/sources_1/bd/image_block/ip/image_block_rst_ps7_0_100M_0/image_block_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_block_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/user/Desktop/project/FPGA/BARN AI/BARN AI.gen/sources_1/bd/image_block/ip/image_block_rst_ps7_0_100M_0/image_block_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_block_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/user/Desktop/project/FPGA/BARN AI/BARN AI.srcs/sources_1/bd/image_block/ip/image_block_rst_ps7_0_100M_0/image_block_rst_ps7_0_100M_0.xci
# IP: The module: 'image_block_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Desktop/project/FPGA/BARN AI/BARN AI.gen/sources_1/bd/image_block/ip/image_block_rst_ps7_0_100M_0/image_block_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_block_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/user/Desktop/project/FPGA/BARN AI/BARN AI.gen/sources_1/bd/image_block/ip/image_block_rst_ps7_0_100M_0/image_block_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_block_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
